# -*- coding: utf-8 -*-
"""digitsImage1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XvPna-IW2XtGnWOl2tSt1FUPFwSkAAo8
"""

import sklearn.datasets
import matplotlib.pyplot as plt

digits = sklearn.datasets.load_digits()

plt.imshow(digits.images[4], cmap="Greys")
plt.show()